import React,{useEffect,useMemo,useState}from'react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
function Field({label,name,value,onChange,required=false,type='text'}){return <label className="field"><span>{label}{required&&<b> *</b>}</span><input name={name} type={type} value={value} onChange={onChange} required={required}/></label>}
function Registration(){
 const [form,setForm]=useState({playerName:'',fatherName:'',age:'',contactNumber:'',email:'',address:'',clubName:'',jerseyNumber:''});
 const [photo,setPhoto]=useState(null),[preview,setPreview]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 const choose=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5242880){setMessage('Photo must be 5MB or smaller.');e.target.value='';return}setPhoto(f);setPreview(URL.createObjectURL(f));setMessage('')};
 const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');try{const b=new FormData();Object.entries(form).forEach(([k,v])=>b.append(k,v));if(photo)b.append('photo',photo);const r=await fetch(API+'/players',{method:'POST',body:b});const d=await r.json();if(!r.ok)throw Error(d.message);setMessage('Registration successful! Your Registration ID is '+d.player.registrationId+'.');setForm({playerName:'',fatherName:'',age:'',contactNumber:'',email:'',address:'',clubName:'',jerseyNumber:''});setPhoto(null);setPreview('');document.getElementById('photo').value=''}catch(x){setMessage(x.message||'Registration failed')}finally{setBusy(false)}};
 return <><header className="hero"><div className="heroShade"><nav><strong>AKFL</strong><a href="/admin">Admin Panel</a></nav><div className="heroText"><div className="eyebrow">WELCOME TO</div><h1>ALL KORANGI<br/>FOOTBALL LEAGUE</h1><p>Official player registration portal</p></div></div></header>
 <main className="card"><div className="cardTitle"><div className="ball">⚽</div><div><h2>Player Registration</h2><p>Free registration • Unlimited players can register</p></div></div>{message&&<div className={message.startsWith('Registration successful')?'success':'error'}>{message}</div>}
 <form onSubmit={submit}><div className="grid"><Field label="Player Name" name="playerName" value={form.playerName} onChange={update} required/><Field label="Father Name" name="fatherName" value={form.fatherName} onChange={update} required/><Field label="Age" name="age" type="number" value={form.age} onChange={update} required/><Field label="Contact Number" name="contactNumber" value={form.contactNumber} onChange={update} required/><Field label="Email Address" name="email" type="email" value={form.email} onChange={update}/><Field label="Club Name" name="clubName" value={form.clubName} onChange={update} required/><Field label="Jersey Number" name="jerseyNumber" type="number" value={form.jerseyNumber} onChange={update} required/></div>
 <label className="field"><span>Address <b>*</b></span><textarea name="address" value={form.address} onChange={update} required rows="3"/></label>
 <label className="upload"><span>Player Photo</span><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/>{preview&&<img src={preview} alt="Player preview"/>}<small>JPG, PNG or WEBP • Maximum 5MB</small></label>
 <label className="check"><input type="checkbox" required/> I confirm that the information provided is correct.</label><button className="primary" disabled={busy}>{busy?'Submitting...':'Submit Player Registration'}</button></form></main><footer>© {new Date().getFullYear()} ALL KORANGI FOOTBALL LEAGUE</footer></>
}
function Admin(){
 const [token,setToken]=useState(localStorage.getItem('akfl_token')||''),[login,setLogin]=useState({username:'',password:''}),[players,setPlayers]=useState([]),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[message,setMessage]=useState('');
 const load=async()=>{const r=await fetch(API+'/players',{headers:{Authorization:'Bearer '+token}});if(r.status===401){localStorage.removeItem('akfl_token');setToken('');return}setPlayers(await r.json())};
 useEffect(()=>{if(token)load()},[token]);
 const doLogin=async e=>{e.preventDefault();const r=await fetch(API+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const d=await r.json();if(!r.ok)return setMessage(d.message);localStorage.setItem('akfl_token',d.token);setToken(d.token)};
 const remove=async id=>{if(!confirm('Delete this player registration?'))return;const r=await fetch(API+'/players/'+id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});const d=await r.json();if(!r.ok)return setMessage(d.message);setSelected(null);setMessage('Player deleted.');load()};
 const downloadPlayers=()=>{const cols=['Registration ID','Player Name','Father Name','Age','Contact Number','Email','Address','Club Name','Jersey Number','Photo URL','Registered At'];const esc=v=>{const s=String(v??'');return /[",\\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};const rows=players.map(p=>[p.registrationId,p.playerName,p.fatherName,p.age,p.contactNumber,p.email,p.address,p.clubName,p.jerseyNumber,p.photoUrl?API.replace('/api','')+p.photoUrl:'',p.createdAt]);const csv=[cols,...rows].map(r=>r.map(esc).join(',')).join('\\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AKFL-All-Players-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};\n const filtered=useMemo(()=>{let x=q.toLowerCase();return players.filter(p=>[p.registrationId,p.playerName,p.fatherName,p.clubName,p.contactNumber].join(' ').toLowerCase().includes(x))},[players,q]);
 if(!token)return <div className="adminLogin"><form className="loginBox" onSubmit={doLogin}><div className="ball big">⚽</div><h1>AKFL Admin</h1><p>Administration panel</p>{message&&<div className="error">{message}</div>}<Field label="Username" name="username" value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} required/><Field label="Password" name="password" type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/><button className="primary">Login</button><a className="back" href="/">← Back to registration</a></form></div>;
 return <div className="adminPage"><header className="adminHeader"><div><strong>ALL KORANGI FOOTBALL LEAGUE</strong><span>Admin Dashboard</span></div><button onClick={()=>{localStorage.removeItem('akfl_token');setToken('')}}>Logout</button></header><main className="dashboard">
 <div className="stats"><div><b>{players.length}</b><span>Total Registered Players</span></div><div><b>{new Set(players.map(p=>p.clubName)).size}</b><span>Clubs</span></div><div><b>{players.filter(p=>new Date(p.createdAt).toDateString()===new Date().toDateString()).length}</b><span>Registered Today</span></div></div>
 <div className="toolbar"><h2>Player Registrations</h2><div className="toolbarActions"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, ID, club, contact..."/><button className="smallBtn" onClick={downloadPlayers} disabled={!players.length}>Download All Players</button></div></div>{message&&<div className="success">{message}</div>}
 <div className="tableWrap"><table><thead><tr><th>ID</th><th>Photo</th><th>Player</th><th>Club</th><th>Contact</th><th>Jersey</th><th>Date</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.registrationId}</td><td>{p.photoUrl?<img className="thumb" src={API.replace('/api','')+p.photoUrl}/>: '—'}</td><td><b>{p.playerName}</b><small>{p.fatherName}</small></td><td>{p.clubName}</td><td>{p.contactNumber}</td><td>#{p.jerseyNumber}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td><td><button className="smallBtn" onClick={()=>setSelected(p)}>View / Print</button><button className="danger" onClick={()=>remove(p.id)}>Delete</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No registrations found.</div>}</div></main>
 {selected&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="printCard"><div className="printTop"><strong>AKFL</strong><span>PLAYER REGISTRATION CARD</span></div>{selected.photoUrl&&<img className="printPhoto" src={API.replace('/api','')+selected.photoUrl}/>}<h2>{selected.playerName}</h2><p>Registration ID: <b>{selected.registrationId}</b></p><div className="details"><p><b>Father:</b> {selected.fatherName}</p><p><b>Age:</b> {selected.age}</p><p><b>Club:</b> {selected.clubName}</p><p><b>Jersey:</b> #{selected.jerseyNumber}</p><p><b>Contact:</b> {selected.contactNumber}</p><p><b>Address:</b> {selected.address}</p></div></div><button className="primary" onClick={()=>window.print()}>Print Registration Card</button></div></div>}</div>
}
export default function App(){return location.pathname.startsWith('/admin')?<Admin/>:<Registration/>}
